### ISSUE TITLE
Reply-by-email crash

### ISSUE THREAD

**Issue by zack-shoylev** [julianlam/nodebb-plugin-emailer-sendgrid#14]
```
uncaughtException: SocketHelpers.notifyOnlineUsers is not a function
TypeError: SocketHelpers.notifyOnlineUsers is not a function
    at Emailer.notifyUsers (/home/saas/nodebb/node_modules/nodebb-plugin-emailer-sendgrid/index.js:163:16)
    at nextTask (/home/saas/nodebb/node_modules/async/dist/async.js:4576:27)
    at next (/home/saas/nodebb/node_modules/async/dist/async.js:4584:13)
    at /home/saas/nodebb/node_modules/async/dist/async.js:321:20
    at /home/saas/nodebb/src/promisify.js:46:33
    at cb (util.js:353:39)
    at process._tickCallback (internal/process/next_tick.js:63:19) {"error":{},"stack":"TypeError: SocketHelpers.notifyOnlineUsers is not a function\n    at Emailer.notifyUsers (/home/saas/nodebb/node_modules/nodebb-plugin-emailer-sendgrid/index.js:163:16)\n    at nextTask (/home/saas/nodebb/node_modules/async/dist/async.js:4576:27)\n    at next (/home/saas/nodebb/node_modules/async/dist/async.js:4584:13)\n    at /home/saas/nodebb/node_modules/async/dist/async.js:321:20\n    at /home/saas/nodebb/src/promisify.js:46:33\n    at cb (util.js:353:39)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Tue May 05 2020 13:55:08 GMT+0000 (Coordinated Universal Time)","process":{"pid":10532,"uid":1000,"gid":1000,"cwd":"/home/saas/nodebb","execPath":"/usr/bin/node","version":"v10.19.0","argv":["/usr/bin/node","/home/saas/nodebb/app.js"],"memoryUsage":{"rss":141361152,"heapTotal":103862272,"heapUsed":95398408,"external":36432010}},"os":{"loadavg":[0.10791015625,0.052734375,0.01171875],"uptime":1628245},"trace":[{"column":16,"file":"/home/saas/nodebb/node_modules/nodebb-plugin-emailer-sendgrid/index.js","function":"Emailer.notifyUsers","line":163,"method":"notifyUsers","native":false},{"column":27,"file":"/home/saas/nodebb/node_modules/async/dist/async.js","function":"nextTask","line":4576,"method":null,"native":false},{"column":13,"file":"/home/saas/nodebb/node_modules/async/dist/async.js","function":"next","line":4584,"method":null,"native":false},{"column":20,"file":"/home/saas/nodebb/node_modules/async/dist/async.js","function":null,"line":321,"method":null,"native":false},{"column":33,"file":"/home/saas/nodebb/src/promisify.js","function":null,"line":46,"method":null,"native":false},{"column":39,"file":"util.js","function":"cb","line":353,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
```

on NodeBB v1.13.2

**Comment by julianlam** [comment]
Thanks for reporting :smile:

**Comment by zack-shoylev** [comment]
Thanks for the instant fix!
